name: PHP Codeception Tests - main

on:
  push:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-master.yml@main
    with:
      module-id: flex-theme
      use-rest-module: false
      install-composer: true
