name: PHP Codeception Tests - master

on:
  pull_request

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-master.yml@main
    with:
      module-id: flex-theme
      use-rest-module: true
      install-composer: true
