name: PHP Codeception Tests - main

on:
  push:
    branches:
      -main
      -develop

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-master.yml@main
    with:
      module-id: flex-theme
      use-rest-module: false
